language: c

env:
    - SMVERSION=1.7
    - SMVERSION=1.8
    - SMVERSION=1.9
    - SMVERSION=1.10

matrix:
    fast_finish: true
    allow_failures:
        - env: SMVERSION=1.7

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib lib32stdc++6 lib32z1 lynx

script:
    - ./scripting/tests/test_compile-all.sh

notifications:
    email: false
